import { gSP } from "src/blitz-server"
import Head from "next/head"
import Link from "next/link"
import Image from "next/image"
import { Routes } from "@blitzjs/next"
import { GetServerSidePropsContext } from "next"
import getCurrentUserServer from "src/users/queries/getCurrentUserServer"
import path from "path"
import LogoBrand from "src/assets/LogoBrand"
import { useState } from "react"
import LandingLayout from "src/core/layouts/LandingLayout"

export const getStaticProps = gSP(async function getStaticProps(context) {
  path.resolve("next.config.js")
  path.resolve("blitz.config.js")
  path.resolve(".next/blitz/db.js")

  return {
    props: {},
  }
})

export default function Cookies() {
  return (
    <LandingLayout title="hire-win | Cookies">
      <section className="px-4">
        <div className="w-full h-full flex justify-center">
          <h1 className="font-bold text-5xl">Cookie Use</h1>
        </div>
        <div className="mt-10 text-justify">
          <h1 className="font-bold">Cookie Policy</h1> <p>Updated at 2022-07-27</p>{" "}
          <p>
            <br />
          </p>{" "}
          <h1 className="font-bold">Definitions and key terms</h1>{" "}
          <p>
            <span>
              To help explain things as clearly as possible in this Cookie Policy, every time any of
              these terms are referenced, are strictly defined as:
            </span>
          </p>{" "}
          <p>
            <br />
          </p>{" "}
          <ul>
            <li>
              <span>
                <strong>Cookie:</strong> small amount of data generated by a website and saved by
                your web browser. It is used to identify your browser, provide analytics, remember
                information about you such as your language preference or login information.
                <br />
              </span>
            </li>{" "}
            <li>
              <span>
                <strong>Company:</strong> when this policy mentions “Company,” “we,” “us,” or “our,”
                it refers to <a>hire.win</a>,{" "}
                <a>
                  202, Parmeshwar Flat, Opp. Champa Tower, Near Rupani Diwadi, Bhavnagar - 364001
                </a>{" "}
                that is responsible for your information under this Cookie Policy.
                <br />
              </span>
            </li>{" "}
            <li>
              <span>
                <strong>Device:</strong> any internet connected device such as a phone, tablet,
                computer or any other device that can be used to visit <a>hire.win</a> and use the
                services.
                <br />
              </span>
            </li>{" "}
            <li>
              <span>
                <strong>Personal Data:</strong> any information that directly, indirectly, or in
                connection with other information — including a personal identification number —
                allows for the identification or identifiability of a natural person.
                <br />
              </span>
            </li>{" "}
            <li>
              <span>
                <strong>Service:</strong> refers to the service provided by <a>hire.win</a> as
                described in the relative terms (if available) and on this platform.
                <br />
              </span>
            </li>{" "}
            <li>
              <span>
                <strong>Third-party service:</strong> refers to advertisers, contest sponsors,
                promotional and marketing partners, and others who provide our content or whose
                products or services we think may interest you.
                <br />
              </span>
            </li>{" "}
            <li>
              <span>
                <strong>Website:</strong> <a>hire.win</a>’s site, which can be accessed via this
                URL: <a>https://hire.win</a>
                <br />
              </span>
            </li>{" "}
            <li>
              <span>
                <strong>You:</strong> a person or entity that is registered with <a>hire.win</a> to
                use the Services.
                <br />
              </span>
            </li>
          </ul>{" "}
          <p>
            <br />
          </p>{" "}
          <h1 className="font-bold">Introduction</h1>{" "}
          <p>
            <span>
              This Cookie Policy explains how <a>hire.win</a> and its affiliates (collectively {`"`}
              <a>hire.win</a>
              {`"`}, {`"`}we{`"`}, {`"`}us{`"`}, and {`"`}ours{`"`}), use cookies and similar
              technologies to recognize you when you visit our platform, including without
              limitation https://hire.win and any related URLs, mobile or localized versions and
              related domains / sub-domains ({`"`}Websites{`"`}). It explains what these
              technologies are and why we use them, as well as the choices for how to control them.
            </span>
          </p>{" "}
          <p>
            <br />
          </p>{" "}
          <h1 className="font-bold">What is a cookie?</h1>{" "}
          <p>
            <span>
              A cookie is a small text file that is stored on your computer or other internet
              connected device in order to identify your browser, provide analytics, remember
              information about you such as your language preference or login information.{" "}
              {`They're`}
              completely safe and {`can't`} be used to run programs or deliver viruses to your
              device.
            </span>
          </p>{" "}
          <p>
            <br />
          </p>{" "}
          <h1 className="font-bold">Why do we use cookies?</h1>{" "}
          <p>
            <span>
              We use first party and/or third party cookies on our platform for various purposes
              such as:
            </span>
          </p>{" "}
          <ul>
            <li>
              <span>To facilitate the operation and functionality of our platform;</span>
            </li>{" "}
            <li>
              <span>
                To improve your experience of our platform and make navigating around them quicker
                and easier;
              </span>
            </li>{" "}
            <li>
              <span>
                To allow us to make a bespoke user experience for you and for us to understand what
                is useful or of interest to you;
              </span>
            </li>{" "}
            <li>
              <span>To analyze how our platform is used and how best we can customize it;</span>
            </li>{" "}
            <li>
              <span>
                To identify future prospects and personalize marketing and sales interactions with
                it;
              </span>
            </li>{" "}
            <li>
              <span>To facilitate the tailoring of online advertising to your interests.</span>
            </li>
          </ul>{" "}
          <p>
            <br />
          </p>{" "}
          <h1 className="font-bold">
            What type of cookies does <a>hire.win</a> use?
          </h1>{" "}
          <p>
            <span>
              Cookies can either be session cookies or persistent cookies. A session cookie expires
              automatically when you close your browser. A persistent cookie will remain until it
              expires or you delete your cookies. Expiration dates are set in the cookies
              themselves; some may expire after a few minutes while others may expire after multiple
              years. Cookies placed by the website you’re visiting are called “first party cookies”.
            </span>
          </p>{" "}
          <p>
            <span>
              Strictly Necessary cookies are necessary for our platform to function and cannot be
              switched off in our systems. They are essential in order to enable you to navigate
              around the platform and use its features. If you remove or disable these cookies, we
              cannot guarantee that you will be able to use our platform.
            </span>
          </p>{" "}
          <p>
            <span>We use the following types of cookies in our platform:</span>
          </p>{" "}
          <p>
            <br />
          </p>{" "}
          <h1 className="font-bold">Essential Cookies</h1>{" "}
          <p>
            <span>
              We use essential cookies to make our platform work. These cookies are strictly
              necessary to enable core functionality such as security, network management, your
              cookie preferences and accessibility. Without them you {`wouldn't`} be able to use
              basic services. You may disable these by changing your browser settings, but this may
              affect how the Websites function.
              <p>
                <br />
              </p>{" "}
              <h1 className="font-bold">Performance and Functionality Cookies</h1>{" "}
              <p>
                <span>
                  These cookies are used to enhance the performance and functionality of our
                  platform but are non-essential to their use. However, without these cookies,
                  certain functionality like videos may become unavailable or you would be required
                  to enter your login details every time you visit the platform as we would not be
                  able to remember that you had logged in previously.
                </span>
              </p>{" "}
              <p>
                <br />
              </p>{" "}
              <h1 className="font-bold">Marketing Cookies</h1>{" "}
              <p>
                <span>
                  These account-based marketing cookies enable us to identify future prospects and
                  personalize sales and marketing interactions with them.
                </span>
              </p>{" "}
              <p>
                <br />
              </p>{" "}
              <h1 className="font-bold">Analytics and Customization Cookies</h1>{" "}
              <p>
                <span>
                  These cookies collect information that is used to help us understand how our
                  platform is being used or how effective our marketing campaigns are, or to help us
                  customize our platform for you.
                  <br />
                  <br />
                  We use cookies served by Google Analytics to collect limited data directly from
                  end-user browsers to enable us to better understand your use of our platform.
                  Further information on how Google collects and uses this data can be found
                  at:&nbsp;https://www.google.com/policies/privacy/partners/. You can opt-out of all
                  Google supported analytics on our Websites by
                  visiting:&nbsp;https://tools.google.com/dlpage/gaoptout.
                </span>
              </p>{" "}
              <p>
                <br />
              </p>{" "}
              <h1 className="font-bold">Social Media Cookies</h1>{" "}
              <p>
                <span>
                  These cookies are used when you share information using a social media sharing
                  button or “like” button on our Site or you link your account or engage with our
                  content on or through a social networking website such as Facebook, Twitter or
                  Google+. The social network will record that you have done this. These cookies may
                  also include certain code that has been placed on the platform to help track
                  conversions from ads, optimize ads based on collected data, build targeted
                  audiences for future ads, and remarket to qualified users who have already taken
                  certain action on the platform.
                </span>
              </p>{" "}
              <p>
                <br />
              </p>{" "}
              <h1 className="font-bold">Third Party Cookies</h1>{" "}
              <p>
                <span>
                  Some cookies that have been set on our platform are not set on a first party basis
                  by <a>hire.win</a>. The Websites can be embedded with content from third parties
                  to serve advertising. These third party service providers may set their own
                  cookies on your web browser. Third party service providers control many of the
                  performance and functionality, advertising, marketing and analytics cookies
                  described above. We do not control the use of these third party cookies as cookies
                  can only be accessed by the third party that originally set them.
                </span>
              </p>{" "}
              <p>
                <br />
              </p>{" "}
              <h1 className="font-bold">How you can manage cookies?</h1>{" "}
              <p>
                <span>
                  Most browsers allow you to control cookies through their {`'settings'`}{" "}
                  preferences. However, if you limit the ability of websites to set cookies, you may
                  worsen your overall user experience, since it will no longer be personalized to
                  you. It may also stop you from saving customized settings like login information.
                  Browser manufacturers provide help pages relating to cookie management in their
                  products.
                </span>
              </p>{" "}
              <br />
              <p>
                <span>
                  Browser manufacturers provide help pages relating to cookie management in their
                  products. Please see below for more information.
                </span>
              </p>{" "}
              <ul>
                <li>
                  <span>Google Chrome</span>
                </li>{" "}
                <li>
                  <span>Internet Explorer</span>
                </li>{" "}
                <li>
                  <span>Mozilla Firefox</span>
                </li>{" "}
                <li>
                  <span>Safari (Desktop)</span>
                </li>{" "}
                <li>
                  <span>Safari (Mobile)</span>
                </li>{" "}
                <li>
                  <span>Android Browser</span>
                </li>{" "}
                <li>
                  <span>Opera</span>
                </li>{" "}
                <li>
                  <span>Opera Mobile</span>
                </li>
              </ul>{" "}
              <p>
                <br />
              </p>{" "}
              <h1 className="font-bold">Blocking and disabling cookies and similar technologies</h1>{" "}
              <p>
                <span>
                  Wherever {`you're`} located you may also set your browser to block cookies and
                  similar technologies, but this action may block our essential cookies and prevent
                  our website from functioning properly, and you may not be able to fully utilize
                  all of its features and services. You should also be aware that you may also lose
                  some saved information (e.g. saved login details, site preferences) if you block
                  cookies on your browser. Different browsers make different controls available to
                  you. Disabling a cookie or category of cookie does not delete the cookie from your
                  browser, you will need to do this yourself from within your browser, you should
                  visit your {`browser's`} help menu for more information.
                </span>
              </p>{" "}
              <p>
                <br />
              </p>{" "}
              <h1 className="font-bold">Changes To Our Cookie Policy</h1>{" "}
              <p>
                <span>
                  We may change our Service and policies, and we may need to make changes to this
                  Cookie Policy so that they accurately reflect our Service and policies. Unless
                  otherwise required by law, we will notify you (for example, through our Service)
                  before we make changes to this Cookie Policy and give you an opportunity to review
                  them before they go into effect. Then, if you continue to use the Service, you
                  will be bound by the updated Cookie Policy. If you do not want to agree to this or
                  any updated Cookie Policy, you can delete your account.
                </span>
              </p>{" "}
              <p>
                <br />
              </p>{" "}
              <h1 className="font-bold">Your Consent</h1>{" "}
              <p>
                <span>
                  By using our platform, registering an account, or making a purchase, you hereby
                  consent to our Cookie Policy and agree to its terms.
                </span>
              </p>{" "}
              <p>
                <br />
              </p>{" "}
              <h1 className="font-bold">Contact Us</h1>{" "}
              <p>
                <span>
                  {`Don't`} hesitate to contact us if you have any questions regarding our Cookie
                  Policy.
                </span>
              </p>{" "}
              <ul>
                <li>
                  <span>
                    Via Email: <a>support@hire.win</a>
                  </span>
                </li>{" "}
              </ul>
            </span>
          </p>
        </div>
      </section>
    </LandingLayout>
  )
}
