import { gSP } from "src/blitz-server"
import LandingLayout from "src/core/layouts/LandingLayout"
import path from "path"

export const getStaticProps = gSP(async function getStaticProps(context) {
  path.resolve("next.config.js")
  path.resolve("blitz.config.js")
  path.resolve(".next/blitz/db.js")

  return {
    props: {},
  }
})

export default function Disclaimer({}) {
  return (
    <LandingLayout title="Hire.win | Disclaimer">
      <div className="w-full h-full flex justify-center">
        <h1 className="font-bold text-5xl">Disclaimer</h1>
      </div>
      <div>
        <h1 className="font-bold">Disclaimer</h1> <p>Updated at 2022-07-27</p>{" "}
        <p>
          <span>
            <a>hire.win</a> hereby grants you access to <a>https://hire.win.</a> (“the Website”) and
            invites you to purchase the services offered here.
          </span>
        </p>{" "}
        <p>
          <br />
        </p>{" "}
        <h1 className="font-bold">Definitions and key terms</h1>{" "}
        <p>
          <span>
            To help explain things as clearly as possible in this Disclaimer, every time any of
            these terms are referenced, are strictly defined as:
          </span>
        </p>{" "}
        <p>
          <br />
        </p>{" "}
        <ul>
          <li>
            <span>
              <strong>Cookie:</strong> small amount of data generated by a website and saved by your
              web browser. It is used to identify your browser, provide analytics, remember
              information about you such as your language preference or login information.
              <br />
            </span>
          </li>{" "}
          <li>
            <span>
              <strong>Company:</strong> when this policy mentions “Company,” “we,” “us,” or “our,”
              it refers to <a>hire.win</a>,{" "}
              <a>202, Parmeshwar Flat, Opp. Champa Tower, Near Rupani Diwadi, Bhavnagar - 364001</a>{" "}
              that is responsible for your information under this Disclaimer.
              <br />
            </span>
          </li>{" "}
          <li>
            <span>
              <strong>Service:</strong> refers to the service provided by <a>hire.win</a> as
              described in the relative terms (if available) and on this platform.
              <br />
            </span>
          </li>{" "}
          <li>
            <span>
              <strong>Website:</strong> <a>hire.win</a>’s site, which can be accessed via this URL:{" "}
              <a>https://hire.win.</a>
              <br />
            </span>
          </li>{" "}
          <li>
            <span>
              <strong>You:</strong> a person or entity that is registered with <a>hire.win</a> to
              use the Services.
              <br />
            </span>
          </li>
        </ul>{" "}
        <p>
          <br />
        </p>{" "}
        <h1 className="font-bold">Limited liability</h1>{" "}
        <p>
          <span>
            We endeavour to update and/or supplement the content of our service on a regular basis.
            Despite our care and attention, content may be incomplete and/or incorrect.
            <br />
            <br />
            The materials we offer are offered without any form of guarantee or claim to their
            correctness. These materials can be changed at any time without prior notice from us.
            <br />
            <br />
            Particularly, all prices on our service are stated subject to typing and programming
            errors. No liability is assumed for the implications of such errors. No agreement is
            concluded on the basis of such errors.
            <br />
            <br />
            We shall not bear any liability for hyperlinks to websites or services of third parties
            included on our service. From our service, you can visit other websites by following
            hyperlinks to such external sites. While we strive to provide only quality links to
            useful and ethical websites, we have no control over the content and nature of these
            sites. These links to other websites do not imply a recommendation for all the content
            found on these sites. Site owners and content may change without notice and may occur
            before we have the opportunity to remove a link which may have gone ‘bad’.
            <br />
            <br />
            Please be also aware that when you leave our service, other sites may have different
            privacy policies and terms which are beyond our control. Please be sure to check the
            Privacy Policies of these sites as well as their {`"`}Terms of Service{`"`} before
            engaging in any business or uploading any information.
          </span>
        </p>{" "}
        <p>
          <br />
        </p>{" "}
        <h1 className="font-bold">Links to Other Websites Disclaimer</h1>{" "}
        <p>
          <span>
            This Disclaimer applies only to the Services. The Services may contain links to other
            websites not operated or controlled by us. We are not responsible for the content,
            accuracy or opinions expressed in such websites, and such websites are not investigated,
            monitored or checked for accuracy or completeness by us. Please remember that when you
            use a link to go from the Services to another website, our Privacy Policy is no longer
            in effect. Your browsing and interaction on any other website, including those that have
            a link on our platform, is subject to that website’s own rules and policies. Such third
            parties may use their own cookies or other methods to collect information about you. If
            You click on a third party link, You will be directed to that third {`party's`} site. We
            strongly advise You to review the Privacy Policy and Terms of every site You visit.
            <br />
            <br />
            We have no control over and assume no responsibility for the content, privacy policies
            or practices of any third party sites or services.
          </span>
        </p>{" "}
        <p>
          <br />
        </p>{" "}
        <h1 className="font-bold">Errors and Omissions Disclaimer</h1>{" "}
        <p>
          <span>
            We are not responsible for any content, code or any other imprecision.
            <br />
            <br />
            We do not provide warranties or guarantees.
            <br />
            <br />
            In no event shall we be liable for any special, direct, indirect, consequential, or
            incidental damages or any damages whatsoever, whether in an action of contract,
            negligence or other tort, arising out of or in connection with the use of the Service or
            the contents of the Service. We reserve the right to make additions, deletions, or
            modifications to the contents on the Service at any time without prior notice.
          </span>
        </p>{" "}
        <p>
          <br />
        </p>{" "}
        <h1 className="font-bold">Copyright Disclaimer</h1>{" "}
        <p>
          <span>
            All intellectual property rights concerning these materials are vested in{" "}
            <a>hire.win</a>. Copying, distribution and any other use of these materials is not
            permitted without the written permission from <a>hire.win</a>, except and only to the
            extent otherwise provided in regulations of mandatory law (such as the right to quote),
            unless otherwise stated for certain materials.
          </span>
        </p>{" "}
        <p>
          <br />
        </p>{" "}
        <h1 className="font-bold">General Disclaimer</h1>{" "}
        <p>
          <span>
            The <a>hire.win</a> Service and its contents are provided {`"`}as is{`"`} and {`"`}as
            available{`"`}
            without any warranty or representations of any kind, whether express or implied.{" "}
            <a>hire.win</a> is a distributor and not a publisher of the content supplied by third
            parties; as such, <a>hire.win</a> exercises no editorial control over such content and
            makes no warranty or representation as to the accuracy, reliability or currency of any
            information, content, service or merchandise provided through or accessible via the{" "}
            <a>hire.win</a> Service. Without limiting the foregoing, <a>hire.win</a> specifically
            disclaims all warranties and representations in any content transmitted on or in
            connection with the <a>hire.win</a> Service or on sites that may appear as links on the{" "}
            <a>hire.win</a> Service, or in the products provided as a part of, or otherwise in
            connection with, the <a>hire.win</a> Service, including without limitation any
            warranties of merchantability, fitness for a particular purpose or non-infringement of
            third party rights. No oral advice or written information given by <a>hire.win</a> or
            any of its affiliates, employees, officers, directors, agents, or the like will create a
            warranty. Price and availability information is subject to change without notice.
            Without limiting the foregoing, <a>hire.win</a> does not warrant that the{" "}
            <a>hire.win</a> Service will be uninterrupted, uncorrupted, timely, or error-free.
          </span>
        </p>{" "}
        <p>
          <br />
        </p>{" "}
        <h1 className="font-bold">Testimonials Disclosure</h1>{" "}
        <p>
          <span>
            Any testimonials provided on this platform are opinions of those providing them. The
            information provided in the testimonials is not to be relied upon to predict results in
            your specific situation. The results you experience will be dependent on many factors
            including but not limited to your level of personal responsibility, commitment, and
            abilities, in addition to those factors that you and/or us may not be able to
            anticipate.
            <br />
            <br />
            We will give honest testimonials to our visitors regardless of any discount. Any product
            or service that we test are individual experiences, reflecting real life experiences.
            The testimonials could be displayed on audio, text or video and are not necessarily
            representative of all of those who will use our products and/or services.
            <br />
            <br /> <a>hire.win</a> does not guarantee the same results as the testimonials given on
            our platform. Testimonials presented on our platform are applicable to the individuals
            writing them, and may not be indicative of future success of any other individuals.
            <br />
            <br />
            Please don’t hesitate to contact us if you would like to know more about testimonials,
            discounts, or any of the products/services that we review.
          </span>
        </p>{" "}
        <p>
          <br />
        </p>{" "}
        <h1 className="font-bold">Your Consent</h1>{" "}
        <p>
          <span>
            {`We've`} updated our Disclaimer to provide you with complete transparency into what is
            being set when you visit our site and how {`it's`} being used. By using our service,
            registering an account, or making a purchase, you hereby consent to our Disclaimer and
            agree to its terms.
          </span>
        </p>{" "}
        <p>
          <br />
        </p>{" "}
        <h1 className="font-bold">Changes To Our Disclaimer</h1>{" "}
        <p>
          <span>
            Should we update, amend or make any changes to this document so that they accurately
            reflect our Service and policies. Unless otherwise required by law, those changes will
            be prominently posted here. Then, if you continue to use the Service, you will be bound
            by the updated Disclaimer. If you do not want to agree to this or any updated
            Disclaimer, you can delete your account.
          </span>
        </p>{" "}
        <p>
          <br />
        </p>{" "}
        <h1 className="font-bold">Contact Us</h1>{" "}
        <p>
          <span>{`Don't`} hesitate to contact us if you have any questions.</span>
        </p>{" "}
        <ul>
          <li>
            <span>
              Via Email: <a>support@hire.win</a>
            </span>
          </li>{" "}
        </ul>
      </div>
    </LandingLayout>
  )
}
