export const FREE_COMPANIES_LIMIT = 1
export const FREE_JOBS_LIMIT = 3
export const FREE_CANDIDATES_LIMIT = 25

// export const LIFETIME_SET1_COMPANIES_LIMIT = 3
// export const LIFETIME_SET1_JOBS_LIMIT = 5
// export const LIFETIME_SET1_CANDIDATES_LIMIT = 100
// export const LIFETIME_SET1_MEMBERS_LIMIT = 5
// export const LIFETIME_SET1_FILES_LIMIT = 5
