export const FREE_JOBS_LIMIT = 3
export const FREE_CANDIDATES_LIMIT = 50

export const LIFETIMET1_JOBS_LIMIT = 5
export const LIFETIMET1_CANDIDATES_LIMIT = 100
export const LIFETIMET1_MEMBERS_LIMIT = 5
export const LIFETIMET1_FILES_LIMIT = 5
