-- AlterTable
ALTER TABLE "Job" ALTER COLUMN "currency" SET DEFAULT E'',
ALTER COLUMN "maxSalary" SET DEFAULT 0,
ALTER COLUMN "minSalary" SET DEFAULT 0,
ALTER COLUMN "salaryType" SET DEFAULT E'YEAR';
