import { EmailTemplate } from "@prisma/client"

const factoryParentEmailTemplates = [
  {
    name: "Apply To Job",
    subject: "Invitation to apply for Job",
    body: {
      blocks: [
        {
          key: "9tqhb",
          data: {},
          text: "Hi {{Candidate_Name}},",
          type: "unstyled",
          depth: 0,
          entityRanges: [],
          inlineStyleRanges: [],
        },
        {
          key: "a67e3",
          data: {},
          text: "",
          type: "unstyled",
          depth: 0,
          entityRanges: [],
          inlineStyleRanges: [],
        },
        {
          key: "77qe3",
          data: {},
          text: "We think you might be a good fit for the job opening of {{Job_Title}} with {{Company_Name}}.",
          type: "unstyled",
          depth: 0,
          entityRanges: [],
          inlineStyleRanges: [],
        },
        {
          key: "1507c",
          data: {},
          text: "",
          type: "unstyled",
          depth: 0,
          entityRanges: [],
          inlineStyleRanges: [],
        },
        {
          key: "9cocr",
          data: {},
          text: "Can you please go through the Job Description and apply to the job by clicking on the below link:",
          type: "unstyled",
          depth: 0,
          entityRanges: [],
          inlineStyleRanges: [],
        },
        {
          key: "3an7j",
          data: {},
          text: "{{Job_Listing_Link}}",
          type: "unstyled",
          depth: 0,
          entityRanges: [],
          inlineStyleRanges: [],
        },
        {
          key: "aajng",
          data: {},
          text: "",
          type: "unstyled",
          depth: 0,
          entityRanges: [],
          inlineStyleRanges: [],
        },
        {
          key: "a5nt",
          data: {},
          text: "Reply back to this email if you have any concerns.",
          type: "unstyled",
          depth: 0,
          entityRanges: [],
          inlineStyleRanges: [],
        },
        {
          key: "anr40",
          data: {},
          text: "",
          type: "unstyled",
          depth: 0,
          entityRanges: [],
          inlineStyleRanges: [],
        },
        {
          key: "7epf2",
          data: {},
          text: "Thanks,",
          type: "unstyled",
          depth: 0,
          entityRanges: [],
          inlineStyleRanges: [],
        },
        {
          key: "j1hc",
          data: {},
          text: "{{Sender_Name}}",
          type: "unstyled",
          depth: 0,
          entityRanges: [],
          inlineStyleRanges: [],
        },
      ],
      entityMap: {},
    } as any,
  } as EmailTemplate,
  {
    name: "Check out Careers Page",
    subject: "Check out our careers page",
    body: {
      blocks: [
        {
          key: "c01j7",
          data: {},
          text: "Hi {{Candidate_Name}},",
          type: "unstyled",
          depth: 0,
          entityRanges: [],
          inlineStyleRanges: [],
        },
        {
          key: "8fsmv",
          data: {},
          text: "",
          type: "unstyled",
          depth: 0,
          entityRanges: [],
          inlineStyleRanges: [],
        },
        {
          key: "2lkb7",
          data: {},
          text: "We received your profile and want you to check out current job openings at our company {{Company_Name}}. Please go through the Job Description and apply to the job that is relevant to your profile. Click on the link below to view our Careers Page:",
          type: "unstyled",
          depth: 0,
          entityRanges: [],
          inlineStyleRanges: [],
        },
        {
          key: "i8ls",
          data: {},
          text: "{{Careers_Page_Link}}",
          type: "unstyled",
          depth: 0,
          entityRanges: [],
          inlineStyleRanges: [],
        },
        {
          key: "jm2a",
          data: {},
          text: "",
          type: "unstyled",
          depth: 0,
          entityRanges: [],
          inlineStyleRanges: [],
        },
        {
          key: "9q87h",
          data: {},
          text: "Reply right back to this email to get in touch with us if you have any queries.",
          type: "unstyled",
          depth: 0,
          entityRanges: [],
          inlineStyleRanges: [],
        },
        {
          key: "begtf",
          data: {},
          text: "",
          type: "unstyled",
          depth: 0,
          entityRanges: [],
          inlineStyleRanges: [],
        },
        {
          key: "fqhvb",
          data: {},
          text: "Thanks,",
          type: "unstyled",
          depth: 0,
          entityRanges: [],
          inlineStyleRanges: [],
        },
        {
          key: "32qho",
          data: {},
          text: "{{Sender_Name}}",
          type: "unstyled",
          depth: 0,
          entityRanges: [],
          inlineStyleRanges: [],
        },
      ],
      entityMap: {},
    } as any,
  } as EmailTemplate,
  {
    name: "Check out Job Board",
    subject: "Check out our Job Board",
    body: {
      blocks: [
        {
          key: "3gl0k",
          data: { "text-align": "start" },
          text: "Hi {{Candidate_Name}},",
          type: "unstyled",
          depth: 0,
          entityRanges: [],
          inlineStyleRanges: [
            { style: "color-rgb(0,0,0)", length: 22, offset: 0 },
            { style: "fontsize-14", length: 22, offset: 0 },
            {
              style:
                'fontfamily-ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, "Noto Sans", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji',
              length: 22,
              offset: 0,
            },
          ],
        },
        {
          key: "6gp1m",
          data: {},
          text: "",
          type: "unstyled",
          depth: 0,
          entityRanges: [],
          inlineStyleRanges: [],
        },
        {
          key: "1m0en",
          data: {},
          text: "This is {{Sender_Name}} from {{Parent_Company_Name}}.",
          type: "unstyled",
          depth: 0,
          entityRanges: [],
          inlineStyleRanges: [
            { style: "color-rgb(0,0,0)", length: 53, offset: 0 },
            { style: "fontsize-14", length: 53, offset: 0 },
            {
              style:
                'fontfamily-ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, "Noto Sans", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji',
              length: 53,
              offset: 0,
            },
          ],
        },
        {
          key: "d5n74",
          data: {},
          text: "",
          type: "unstyled",
          depth: 0,
          entityRanges: [],
          inlineStyleRanges: [],
        },
        {
          key: "bclro",
          data: {},
          text: "We received your profile and want you to check out current job openings at multiple companies. Please go through the Job Description and apply to the job that is relevant to your profile. Click on the link below to view our Job Board:",
          type: "unstyled",
          depth: 0,
          entityRanges: [],
          inlineStyleRanges: [
            { style: "color-rgb(0,0,0)", length: 234, offset: 0 },
            { style: "fontsize-14", length: 234, offset: 0 },
            {
              style:
                'fontfamily-ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, "Noto Sans", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji',
              length: 234,
              offset: 0,
            },
          ],
        },
        {
          key: "2grit",
          data: {},
          text: "{{Job_Board_Link}}",
          type: "unstyled",
          depth: 0,
          entityRanges: [],
          inlineStyleRanges: [
            { style: "color-rgb(0,0,0)", length: 18, offset: 0 },
            { style: "fontsize-14", length: 18, offset: 0 },
            {
              style:
                'fontfamily-ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, "Noto Sans", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji',
              length: 18,
              offset: 0,
            },
          ],
        },
        {
          key: "f1jtq",
          data: {},
          text: "",
          type: "unstyled",
          depth: 0,
          entityRanges: [],
          inlineStyleRanges: [],
        },
        {
          key: "1ito0",
          data: { "text-align": "left" },
          text: "Reply right back to this email to get in touch with us if you have any queries.",
          type: "unstyled",
          depth: 0,
          entityRanges: [],
          inlineStyleRanges: [
            { style: "color-rgb(0,0,0)", length: 79, offset: 0 },
            { style: "fontsize-14", length: 79, offset: 0 },
            {
              style:
                'fontfamily-ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, "Noto Sans", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji',
              length: 79,
              offset: 0,
            },
          ],
        },
        {
          key: "eumb9",
          data: {},
          text: "",
          type: "unstyled",
          depth: 0,
          entityRanges: [],
          inlineStyleRanges: [],
        },
        {
          key: "kvbf",
          data: {},
          text: "Thanks,",
          type: "unstyled",
          depth: 0,
          entityRanges: [],
          inlineStyleRanges: [
            { style: "color-rgb(0,0,0)", length: 7, offset: 0 },
            { style: "fontsize-14", length: 7, offset: 0 },
            {
              style:
                'fontfamily-ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, "Noto Sans", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji',
              length: 7,
              offset: 0,
            },
          ],
        },
        {
          key: "d2jgm",
          data: {},
          text: "{{Sender_Name}}",
          type: "unstyled",
          depth: 0,
          entityRanges: [],
          inlineStyleRanges: [
            { style: "color-rgb(0,0,0)", length: 15, offset: 0 },
            { style: "fontsize-14", length: 15, offset: 0 },
            {
              style:
                'fontfamily-ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, "Noto Sans", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji',
              length: 15,
              offset: 0,
            },
          ],
        },
      ],
      entityMap: {},
    } as any,
  } as EmailTemplate,
]

export default factoryParentEmailTemplates
